### ISSUE TITLE
Question about Data format

### ISSUE THREAD

**Issue by rungjoo** [facebookresearch/simmc2#1]
Hello. I am a DSTC10 participant.

Thanks for the data release.

After downloading and checking the data, it is currently stored as follows in simmc2_dials_dstc10_train.json.
![image](https://user-images.githubusercontent.com/48037590/122320446-300d0580-cf5d-11eb-947b-a13aef39130a.png)

It's different from what you described in the data introduction. Is there an update?
![image](https://user-images.githubusercontent.com/48037590/122320474-3bf8c780-cf5d-11eb-8b68-890ce14079cb.png)

Thank you.

**Comment by ShiZhengyan** [comment]
Yes, the data format is different.

**Comment by satwikkottur** [comment]
Hello all,

Thanks for your interest. There was some error copying the right files, apologies for the inconvenience. Feel free to open the comment again if the problem persists.
