### ISSUE TITLE
Question on inference and retrieval

### ISSUE THREAD

**Issue by bambidz** [facebookresearch/simmc2#10]
Hi,

Is the scene.json (cloth_store_1416238_woman_10_0_scene.json) which has the up,down,left,right relationships of the objects useable during inference?
I understand that I can use the bbox information but not the meta data.

Also, 
There was retrieval included in the  Response Generation subtask, but the retrieval candidate seems to be not released yet?
Is there a plan for its release?

Thanks in advance!

**Comment by satwikkottur** [comment]
Hello @bambidz ,

Apologies for the delayed response.

We release the allowed inputs for each task [here](https://github.com/facebookresearch/simmc2/blob/master/TASK_INPUTS.md). Please go through it and feel free to re-open this issue if you have more questions. 

Thanks for your interest!
