### ISSUE TITLE
Error bbox

### ISSUE THREAD

**Issue by rungjoo** [facebookresearch/simmc2#11]
An error occurred while processing image data, so I took a look.

The bbox of object 98 in the file "cloth_store_1416238_woman_11_0" seems to be incorrect.

When I save as below, it seems that the bbox is not displayed properly. The value of bbox is [780, 603, 2, 0].

![image](https://user-images.githubusercontent.com/48037590/124443532-b8423600-ddb8-11eb-8c34-84c87f01116d.png)

Please confirm.
Thanks

**Comment by satwikkottur** [comment]
Hello @rungjoo ,

Thanks for bringing this our notice. It is indeed the case that about 61 (out of 43433)~0.1% bounding boxes has one of their height or width as zero. Kindly ignore these bounding boxes.

Feel free to re-open this issue if ignoring these bounding boxes causes downstream issues.
