### ISSUE TITLE
Error at mm_dst's run_evaluate_gpt2.sh

### ISSUE THREAD

**Issue by heyzude** [facebookresearch/simmc2#13]
At `model/mm_dst/run_evalutate_gpt2.sh`, argument inputs for `input_path_target` and `input_path_predicted` are same, to be `"${PATH_DIR}"/gpt2_dst/data/simmc2_dials_devtest_target.txt`.  
For `input_path_predicted` argument, it should be `"${PATH_DIR}"/gpt2_dst/data/simmc2_dials_devtest_predicted.txt`.
You may also amend the README file of model accordingly.

**Comment by satwikkottur** [comment]
Hello @heyzude ,

Thanks for raising this. The latest commit fixes this.
