### ISSUE TITLE
Parse Error on model/mm_dst/gpt2_dst/utils/convert.py

### ISSUE THREAD

**Issue by han0ah** [facebookresearch/simmc2#14]
There is an error on **parse_flattened_result** function in **model/mm_dst/gpt2_dst/utils/convert.py**

This function returns empty array when it handles **strings contain nested square bracktes.**

e.g.) ".. INFORM:GET **[** sleeveLength = short, availableSizes = **[**'XXL', 'S', 'L'**]**, pattern = leafy design, type = blouse **]** (availableSizes, pattern) < 86, 57 > <EOB>  ... "

**Comment by satwikkottur** [comment]
Hello @han0ah ,

Thanks for pointing this out. We have a fix for this issue and will push it out soon. Thank you for your patience.

**Comment by shanemoon** [comment]
Hello @han0ah, the [recent commit](https://github.com/facebookresearch/simmc2/commit/661e6f0467abf0f1586c409c56e27dac43f67a89) should fix this problem. Thank you for raising this issue!
