### ISSUE TITLE
Using system's object id at subtask2

### ISSUE THREAD

**Issue by rungjoo** [facebookresearch/simmc2#15]
Looking at the baseline mm_dst model you provided (subtask 2&3), it uses the "object id" associated with the previous system utterance. Is it okay to use this in tests as well?

Example
- User : Do you have any shirts with good reviews? System : There are three shirts on the display table: a blue and white, a brown, and a grey and brown. _**<SOM> 37, 40, 12 <EOM>**_ User : Do you have anything with a similar size as the brown shirt and the grey and brown?

Thanks

**Comment by satwikkottur** [comment]
Hello @rungjoo ,

Thanks for your interest. We have released the allowed set of inputs for each task [here][task_input]. Please take a look at the file and feel free to re-open this issue if you have any further questions.

[task_input]:https://github.com/facebookresearch/simmc2/blob/master/TASK_INPUTS.md
