### ISSUE TITLE
Meaning of "url (raw image)" at TASK_INPUTS.md

### ISSUE THREAD

**Issue by heyzude** [facebookresearch/simmc2#20]
![image](https://user-images.githubusercontent.com/12981081/127264636-782b032b-d5da-44bf-bac3-1799372a0122.png)

what is ** url (raw image) ** ? Does this just mean that we can use scene images at training?

**Comment by shanemoon** [comment]
Hi @heyzude, correct, it just means that participants can use the raw scene images ([zip1](https://github.com/facebookresearch/simmc2/blob/master/data/simmc2_scene_images_dstc10_public_part1.zip), [zip2](https://github.com/facebookresearch/simmc2/blob/master/data/simmc2_scene_images_dstc10_public_part2.zip)), ***both*** at training and at inference time. 

We will change the wording to avoid confusion.
