### ISSUE TITLE
Targets stated in TASK_INPUT.md does not match preprocessing code.

### ISSUE THREAD

**Issue by bambidz** [facebookresearch/simmc2#22]
![image](https://user-images.githubusercontent.com/38829593/127276790-e3e6e501-a4a9-4a08-b0b4-e8bb87e1cfa0.png)
It is stated that system_transcript_annotated is used as prediction target.

![image](https://user-images.githubusercontent.com/38829593/127277356-46801e84-5fc9-404e-ac2e-e4bedbb07c2e.png)
![image](https://user-images.githubusercontent.com/38829593/127277365-36101e9a-8794-4278-9ac3-32957f9ac3ad.png)
However in the code given for preprocessing, the prediction target is from transcript_annotation which is from the user's.

There needs to be clarification on which is the correct prediction target.

**Comment by shanemoon** [comment]
Hi @bambidz, thank you for raising this issue. There was a mistake in the recent commit -- we just fixed it to indicate that the prediction targets are `transcript_annotation`.
