### ISSUE TITLE
Are "prefab_path

### ISSUE THREAD

**Issue by heyzude** [facebookresearch/simmc2#24]
![image](https://user-images.githubusercontent.com/12981081/127264636-782b032b-d5da-44bf-bac3-1799372a0122.png)

what is ** url (raw image) ** ? Does this just mean that we can use scene images at training?

**Comment by satwikkottur** [comment]
Hello @heyzude , that is correct! 
By `url (raw image)`, we mean that scene images can be used at inference time. Feel free to use any information at train time (as mentioned in the [task inputs][task_inputs]).

[task_inputs]:https://github.com/facebookresearch/simmc2/blob/master/TASK_INPUTS.md
