### ISSUE TITLE
Are "prefab_path" and "name" of an object allowed at inference time?

### ISSUE THREAD

**Issue by heyzude** [facebookresearch/simmc2#25]
Are "prefab_path"(in scene json file) and "name"(in scene json file and metafile) of an object allowed at inference time?

**Comment by satwikkottur** [comment]
Hello @heyzude ,

Thanks for your interest. You may use `prefab_path` and `name` (in scene JSON file and metafile) only to look-up allowed non-visual attributes from the metafile, but not in isolation `prefab_path` and `name`. This is ensure that participants do not unfairly use these names and extract the type (`skirt_03` -> `skirt` type). 

Feel free to re-open this issue if you have followups.
