### ISSUE TITLE
Is Human evaluation also considered?

### ISSUE THREAD

**Issue by heyzude** [facebookresearch/simmc2#26]
Hi, Is human evaluation is also part of evaluations, along with BLEU, F1?
For reponse genereration, I think generated response with high BLEU score does not guarantee that response is appropriate. In this case human evaluation may step in.

**Comment by satwikkottur** [comment]
Hello @heyzude ,

Totally agree with you that human evaluation is more appropriate and accurate for response generation. However, we do not have any current plans to incorporate human evaluation for this challenge.

Will let you know if things change. Thanks for the suggestion! 
(Feel free to reopen the issue if there are followups)
