### ISSUE TITLE
About object images at the final test session

### ISSUE THREAD

**Issue by heyzude** [facebookresearch/simmc2#28]
This is a bit sensitive question... please excuse me.
I wonder whether images which are available now are re-used at final test session, since if images are reused, figuring out visual metadatas would be reduced to just remembering the clothes and furnitures (this is hard though, because  there are many objects in all scenes). I ask this because scene images may differ but objects inside maybe reused.

**Comment by satwikkottur** [comment]
Hello @heyzude ,

The images and scene JSONs for all the splits (`train`, `devtest`, `dev`, and `teststd`) will be ensured to be disjoint. However, the objects themselves (clothes / furnitures) would most likely overlap. 

Does this answer your question? Feel free to reopen the issue if you have follow-ups.
