### ISSUE TITLE
Do you provide the same scene images and jsons files for both train and test?

### ISSUE THREAD

**Issue by heyzude** [facebookresearch/simmc2#29]
Are images and jsons shown at train time also used at test(inference) time? Or different set of images and jsons are used at test time?

**Comment by satwikkottur** [comment]
Hello @heyzude,

We tried to ensure that the images included in `train` and `devtest` splits are disjoint. The same will be the case with `teststd` as well. Hope this answers the question, feel free to re-open if you have follow-ups.
