### ISSUE TITLE
I have a question about json data in public.

### ISSUE THREAD

**Issue by rungjoo** [facebookresearch/simmc2#3]
I have a question about json data in public.

1. What do each of the four values in bbox represent? 
   - How do I change the bbox+position to (left, top, right, bottom)?
2. Does relationships represent a relationship between indices?
3. What is the difference between unique_id and index?

Thank you.

**Comment by satwikkottur** [comment]
Hello @rungjoo , 

Thanks for your interest. We've added more clarity around these questions in `data/README.md` and included `models/utils/visualize_bbox.py` script to visualize bounding boxes. This should address your concerns, feel free to re-open this issue if you still have questions.

Thanks!

**Comment by tungngthanh** [comment]
I still confuse about the data. My aim is to know which object/scene corresponds to each dialogue.
So I take one example to verify whether I understand right:
```
{
'dialogue_idx': 11564, 
'domain': 'fashion', 
'mentioned_object_ids': [36, 42, 14, 21, 23, 26, 29],
 'scene_ids': {'0': 'm_cloth_store_1416238_woman_3_8', '6': 'm_cloth_store_1416238_woman_3_0'}
}
```

This is from the first data point in devtest dataset.
Is it right to interpret like that: from turn_idx 0 to turn_idx 5, we refer to the **meta** file "**cloth_store_1416238_woman_3_8**_scene.json" and the scene "**cloth_store_1416238_woman_3_8**.png"?

But I cannot find the first file in the data. 
Did I miss something?

**Comment by satwikkottur** [comment]
Hello @tungngthanh ,

Thanks for your interest.

Your interpretation about the scene files is correct.
`turn_idx` 0 to 5 use `m_cloth_store_1416238_woman_3_8`, while 6 onwards use `m_cloth_store_1416238_woman_3_0`.

Since these are multiple scene files per dialog, we have the `m_` prefix. You should be able to find `m_cloth_store_1416238_woman_3_8_scene.json` file in the released JSON files (checked it at my end).

Please feel free to reopen the issue for follow-up questions.

**Comment by tungngthanh** [comment]
> Hello @tungngthanh ,
> 
> Thanks for your interest.
> 
> Your interpretation about the scene files is correct.
> `turn_idx` 0 to 5 use `m_cloth_store_1416238_woman_3_8`, while 6 onwards use `m_cloth_store_1416238_woman_3_0`.
> 
> Since these are multiple scene files per dialog, we have the `m_` prefix. You should be able to find `m_cloth_store_1416238_woman_3_8_scene.json` file in the released JSON files (checked it at my end).
> 
> Please feel free to reopen the issue for follow-up questions.

Thank you for your reply. Follow your suggestions, I find that each scene idx corresponds to one json file and one image file.
However, now I face some problems when I mapped the `object_local_id` to the canonical `object_id`. 
For example, the `third` dialogue (`index 2`) in the training set which has the `scene_ids` as follows:
{'0': 'm_cloth_store_1498649_woman_5_3',
 '5': 'm_cloth_store_1498649_woman_5_9'}
its 7th uterance is :
{
'turn_idx': 6,
 'system_transcript': "Sure, I'll add that now.",
 'system_transcript_annotated': {'act': 'CONFIRM:ADD_TO_CART',
  'act_attributes': {'slot_values': {}, 'request_slots': [], 'objects': [55]}},
 'transcript': 'Actually, just add that brown jacket to my cart.',
 'transcript_annotated': {'act': 'REQUEST:ADD_TO_CART',
  'act_attributes': {'slot_values': {}, 'request_slots': [], 'objects': [55]}}
}
According to the document, we should expect to see the `local_id` 55 object in `m_cloth_store_1498649_woman_5_9_scene.json`, right?
However, when I load the file, I do not see 55 in `index` or `unique_id`.
Can you clarify it for me?
