### ISSUE TITLE
Missing Object IDs

### ISSUE THREAD

**Issue by JChiyah** [facebookresearch/simmc2#30]
Hi,

I am facing the issue that some object IDs do not appear in the scene file for that dialogue. For example, in `m_cloth_store_1498649_woman_5_9`, there is a reference to object ID 55, but there is no object ID 55 either as `index` or `unique_id`. Could you please clarify this?

This question was also asked by @tungngthanh, (quoted below), as the issue was closed without an answer.

After a quick count, this happens ~615 times in the train split: the target object ID does not appear in the scene or bbox jsons for that dialogue.

Thank you.

EDIT: if I include the objects in `system_transcript_annotated` and `transcript_annotated` together, ~3183 entries (user utterance + dialogue history up to that point) make references to objects that do not appear in the respective scene jsons, around 8% of the train data. I am skipping these for now. 

> Thank you for your reply. Follow your suggestions, I find that each scene idx corresponds to one json file and one image file.
> However, now I face some problems when I mapped the `object_local_id` to the canonical `object_id`. 
For example, the `third` dialogue (`index 2`) in the training set which has the `scene_ids` as follows:
{'0': 'm_cloth_store_1498649_woman_5_3',
 '5': 'm_cloth_store_1498649_woman_5_9'}
its 7th uterance is :
{
'turn_idx': 6,
 'system_transcript': "Sure, I'll add that now.",
 'system_transcript_annotated': {'act': 'CONFIRM:ADD_TO_CART',
  'act_attributes': {'slot_values': {}, 'request_slots': [], 'objects': [55]}},
 'transcript': 'Actually, just add that brown jacket to my cart.',
 'transcript_annotated': {'act': 'REQUEST:ADD_TO_CART',
  'act_attributes': {'slot_values': {}, 'request_slots': [], 'objects': [55]}}
}
According to the document, we should expect to see the `local_id` 55 object in `m_cloth_store_1498649_woman_5_9_scene.json`, right?
However, when I load the file, I do not see 55 in `index` or `unique_id`.
Can you clarify it for me?

_Originally posted by @tungngthanh in https://github.com/facebookresearch/simmc2/issues/3#issuecomment-896868063_

**Comment by shanemoon** [comment]
Hi @JChiyah, we apologize for getting back to this issue late. 

This behavior may happen when there are multiple scene IDs associated within each dialogue, which can be regarded essentially as USERs having different viewpoints within the same physical store (e.g. `m_cloth_store_1498649_woman_5_3` and `m_cloth_store_1498649_woman_5_9`). USERs *typically* describe the items in their current viewpoint, but they may also occasionally mention / refer to an item that they have mentioned from a previous viewpoint (e.g. "How much was the blue shirt I saw earlier again?"). Please also note that the object IDs within those two scenes should be consistent (i.e. if the same item appears in multiple scenes/viewpoints from a single dialogue, their object ID should be the same).

In this specific example (`dialogue_idx: 10541` - or the third dialogue in the training set):
```
{'0': 'm_cloth_store_1498649_woman_5_3',
'5': 'm_cloth_store_1498649_woman_5_9'}
```
Object ID `55` (`turn_idx`: 6) was included in `m_cloth_store_1498649_woman_5_3` but not in `m_cloth_store_1498649_woman_5_9`. In this case the participants can resolve this object by looking at the objects mentioned in the previous turns of the dialogue (e.g. Object ID `55` was mentioned at `turn_idx: 2`, while at the `m_cloth_store_1498649_woman_5_3` viewpoint).

Thank you and please let us know if this explanation does not cover your issue. We will clarify this in the doc.

**Comment by JChiyah** [comment]
That makes sense, thanks for the clarification!
