### ISSUE TITLE
Format about subtask 1, 4

### ISSUE THREAD

**Issue by rungjoo** [facebookresearch/simmc2#36]
I understand the output for subtasks 2 and 3.

But I have an output question for subtask1 and 4.

1. The disambiguator_evaluation.py of subtask 1 doesn't exist yet. Will it be updated?

2. What format is the output of subtask1 and 4? (dstc10-simmc-teststd-pred-subtask-1.json/dstc10-simmc-teststd-pred-subtask-4-generation.json/dstc10-simmc-teststd-pred-subtask-4-retrieval.json)

Also, the "data_json_path" in response_evaluation does not exist in the current version.
![image](https://user-images.githubusercontent.com/48037590/133607921-1f16f64f-492a-4781-98aa-cb80668ec976.png)

**Comment by satwikkottur** [comment]
Hello @rungjoo,

1. We will upload this soon, thanks for your patience.

2. We will update the [SUBMISSION_INSTRUCTIONS.md][submission_details] to include the output formats. Until then, please find the formats for subtask 4 here -- [retrieval][retrieval_format] and [generation][generation_format].

3. (Screenshot) The default path is just a placeholder. Could you please try `data/simmc2_dials_dstc10_devtest.json`  to evaluate on [devtest][devtest]?

[submission_details]:https://github.com/facebookresearch/simmc2/blob/master/SUBMISSION_INSTRUCTIONS.md
[retrieval_format]:https://github.com/facebookresearch/simmc2/blob/master/model/utils/retrieval_evaluation.py#L5
[generation_format]:https://github.com/facebookresearch/simmc2/blob/master/model/utils/response_evaluation.py#L5
[devtest]:https://github.com/facebookresearch/simmc2/blob/master/data/simmc2_dials_dstc10_devtest.json
