### ISSUE TITLE
There is no training dataset for Response retrieval

### ISSUE THREAD

**Issue by heyzude** [facebookresearch/simmc2#38]
For Response retrieval subtask, there is no training dataset.

Maybe I can finetune the retrieval model with dev split, but I guess this is against the track rule. Am I right?

Since there is no train dataset, I guess the intention is to re-use the model trained for other subtasks, to solve response retrieval subtask. Is it correct?

Thank you :)

**Comment by shanemoon** [comment]
Hi @heyzude, thank you for your question!

While we did not release the official retrieval candidates for the training of a model, the intention was that the participants can use any of the utterances in the `simmc2_dials_dstc10_train.json` data file as retrieval candidates for training. The rationale was to give as much flexibility as possible to the participants (e.g. in choosing the retrieval sample size for training, retrieval candidate selection strategies, etc.) as it can largely impact the model performance.

Please also feel free to re-use the model trained for other subtasks (e.g. response generation combined with similarity-based retrieval). Thank you and please let us know if you have any other questions!
