### ISSUE TITLE
evaluate_dst cannot be used for task 3

### ISSUE THREAD

**Issue by lyleguo** [facebookresearch/simmc2#39]
The dict structure used in evaluate_dst is not the same as the .json file.
For example, there is no 'belief_state'. There are also many other mismatches.
Could you please state the exact format we should use?

**Comment by shanemoon** [comment]
Hi @lyleguo, thank you for spotting this error in the JSON evaluation of the script. The [latest commit](https://github.com/facebookresearch/simmc2/commit/3183c532d6effaaa5e5808f0e4b509ae5c819bb7) should fix this error.

Please also note that there are two versions of evaluation for DST, which are both acceptable: (1) evaluation based on the flattened .txt results, which the provided baselines use, or (2) evaluation based on the .JSON files (formatted the same as the original data file) - which this fix addresses. You can therefore submit your model prediction results in either format for the challenge (Read more: [Submission Instructions](https://github.com/facebookresearch/simmc2/blob/master/SUBMISSION_INSTRUCTIONS.md)). 

Thank you and please let us know if there is any other issue!
