### ISSUE TITLE
 Some inconsistencies in evaluation scripts

### ISSUE THREAD

**Issue by i2r-simmc** [facebookresearch/simmc2#40]
When I convert the flat text format into submission format, I see some inconsistencies in evaluation scripts.
Can you clarify for me?
**Subtask 1**
In ./model/utils/disambiguator_evaluation.py line [46](https://github.com/facebookresearch/simmc2/blob/master/model/utils/disambiguator_evaluation.py#L46):

```assert "disambiguation_label" in gt_datum, "Turn not to be evaluated!"```

This line will make the error when the groundtrue data do not have disambiguation_label. 
A lot of dialogue turn do not have the label so it causes the error when evaluating the dataset.

**Subtask 3**
In ./model/mm_dst/utils/evaluate_dst.py line [272]
(https://github.com/facebookresearch/simmc2/blob/master/model/mm_dst/utils/evaluate_dst.py#L272)

```true_frame_object_values == pred_frame_object_values```

I think the n_correct_beliefs should not be related to frame_object_values, right?

**Subtask 4**
In ./model/utils/retrieval_evaluation.py
According to the code, the expected format should be

```
 [
    "dialog_id": <dialog_id>,
    "candidate_scores": [
        {
            "turn_id": <turn_id>,
            "scores": [
                <list of 100 floats>
            ]
        }
        ...
    ]
    ...
]
```

**Comment by satwikkottur** [comment]
Hello @i2r-simmc 

Thanks for raising these issues. 

**Subtask 1**
The model is expected to predict the disambiguation label only for the turns where `disambiguation_label` exists and **not** all turns. Sorry if this was not clear.

**Subtask 4**
Agreed! Will make these changes in the documentation.

**Comment by tungngthanh** [comment]
Hello @satwikkottur
In **Subtask 1**, we should change the line into `continue` so that the evaluation script would skip the turn where disambiguation_label does not exist

**Comment by satwikkottur** [comment]
Hello @tungngthanh ,

The evaluation script for subtask 1 excepts to see only turns where the `disambiguation_label` is provided, hence the assertion. If your model predicts the disambiguation label for each turn, you could consider trimming your output file before using the official evaluation script.

Does this address your concern?

**Comment by tungngthanh** [comment]
Hi @satwikkottur,
That line asserts whether the `disambiguatiion_label` is provided in the **ground true file**, not the output file.
Whether I trim my output file is irrelevant here.

**Comment by satwikkottur** [comment]
Hello @tungngthanh ,

Sorry if I was not clear before. Here's a detailed explanation of what I mean:

1. From the header, the output format is:
```
[
    "dialog_id": <dialog_id>,
    "predictions": [
        {
            "turn_id": <turn_id>,
            "disambiguation_label": <bool>,
        }
        ...
    ]
    ...
]
```
2. These [lines][instance_looper] loop over `dialog_id`s and specific `turn_id`s present in the model output file.
```python
for model_datum in model_results:
        dialog_id = model_datum["dialog_id"]
        for round_datum in model_datum["predictions"]:
```
3. For each of these instances, we obtain the corresponding ground truth dictionary `gt_datum` and then check for existence of `disambiguation_label`. 

Therefore, by trimming the model output file and only including relevant `dialog_id` and `turn_id` (in `predictions`), we can avoid triggering these assertions on turns without the label. 

Please let me know if you have follow-up questions.

[instance_looper]:https://github.com/facebookresearch/simmc2/blob/master/model/utils/disambiguator_evaluation.py#L39

**Comment by tungngthanh** [comment]
Hi @satwikkottur,
I think you misunderstand here. 
The issue happens in step 3.
Let's consider a simple example as follows:

In one instance, my **output** for a specific `dialog_id` and `turn_id ` has `disambiguation_label `. However, the corresponding **ground true instance**  ( for that `dialog_id` and `turn_id `) does not have `disambiguation_label `. It would trigger the assertion.
Therefore to avoid triggering the assertion, my output needs to trim the instances not having `disambiguation_label ` in the **ground true file**. It does not make sense at all.

I think we just simply replace the line with 
`if not "disambiguation_label" in gt_datum:
                continue`

**Comment by ggoggam** [comment]
I was also wondering about this. The subtask suggested this would be a binary classification problem. If we had to know which turn to predict at inference time, this would be a ternary classification problem. I think we can simply ignore predictions for turns without `disambiguation_label` at evaluation as @tungngthanh suggested.

**Comment by satwikkottur** [comment]
Hello @tungngthanh and @jkgrad ,

For the purposes of this challenge, the released `test-std` set would contain the key `disambiguation_label` (set to `None`) to indicate the turns on which to run your trained binary classifier. Please report the results of your model only on these turns.

The evaluation script would then compute the corresponding model performance without triggering the assertion. 

Please let me know if this does not address your concerns.

SUBMISSION_DETAILS [here] has been updated last week to clarify this for subtask 1. (https://github.com/facebookresearch/simmc2/blob/master/SUBMISSION_INSTRUCTIONS.md).
