### ISSUE TITLE
Question about subtask1

### ISSUE THREAD

**Issue by rungjoo** [facebookresearch/simmc2#5]
Hello.

When I solve subtask1, I have a question.

subtask2 needs to find an object reference corresponding to the current utterance.

Is this multimodal information available in subtask1?
That is, when predicting disambiguation, is it okay to use multimodal information (e.g. object bounding bbox and metatdata) corresponding to the current utterance? Or can I just use information about the whole image corresponding to the dialog?

Thank you.

**Comment by shanemoon** [comment]
Hi @rungjoo, thank you for your question & your interest in the SIMMC2 track. 

At the training time, you can use all of the multimodal information to train your model.

At the inference time, participants can use the object bbox information, but not the ground-truth metadata (e.g. color, pattern, etc.). Models will have to infer this information from a vision model.

We will soon post a doc that summarizes & clarifies what input fields are allowed at training / inference time. Thank you for your patience!

**Comment by rungjoo** [comment]
Thank you for answer.

Then, when inferring in subtask2,3,4, the bbox is also available but the metadata (e.g. color, pattern, etc) is not available?

**Comment by satwikkottur** [comment]
Hello @rungjoo,

We have uploaded the inputs for each task [here](https://github.com/facebookresearch/simmc2/blob/master/TASK_INPUTS.md). Feel free to reopen the issue if you have more questions.
