### ISSUE TITLE
what does "all", "dress" mean in disambiguation_candidates_raw ?

### ISSUE THREAD

**Issue by bambidz** [facebookresearch/simmc2#53]
![image](https://user-images.githubusercontent.com/38829593/181684294-b638e388-5179-4152-a64f-22d49f0bd066.png)

"disambiguation candidate raw" seems to narrow down the object subspace. Normally, discrete indexes are listed, but there are times where the values are "all", "blouse", "dress" etc. What does these string type values mean?

I guessed that "all" and "blouse" would mean all blouses in the given scene.
I'm also curious if "disambiguation candidate raw" could be used at testing.

**Comment by satwikkottur** [comment]
Hello @bambidz ,

Thanks for your interest.
* `disambiguation_candidates_raw` refer to the processed raw annotations marked by the annotators when identifying the ambiguous objects.
* `disambiguation_candidates` are the mapping of `disambiguation_candidates_raw`, and the former will be used for evaluation. We provide the latter for additional training signals if teams want to leverage it.

At test time, you are not allowed to use either `disambiguation_candidates` or `disambiguation_candidates_raw` as both of these contain information about the target (ambiguous candidates) for this task.

Please re-open this issue if anything is unclear.
