### ISSUE TITLE
Dataloader for subtask 4

### ISSUE THREAD

**Issue by Manuelvh44** [facebookresearch/simmc2#58]
Hello,

I just wanted to ask if there is a specific dataloader for subtask 4 or if we have to implement it ourselves.

Best regards
Manuel

**Comment by Xiao-wen-Sun** [comment]
Same question !

**Comment by shanemoon** [comment]
Hi @Manuelvh44, @HRI-sxw -- we don't currently provide an official (PyTorch style) dataloader specific to subtask 4. Please note that the [MM-DST](https://github.com/facebookresearch/simmc2/tree/main/model/mm_dst) folder does include a script for iterating through data points for input / responses. Thank you!
