### ISSUE TITLE
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by Xiao-wen-Sun** [facebookresearch/simmc2#59]
Hi,
 I tried to run 
3. Generate prediction for devtest data
$ ./run_generate_gpt2.sh

It always failed. 
Here is the screenshot.
![simmc2 1 error](https://user-images.githubusercontent.com/86380173/190210664-e1633e07-a733-4359-8f54-c246713fab88.png)

**Comment by shanemoon** [comment]
Hi @HRI-sxw - I am not able to repro this on my machine -- to help debug, would you mind sharing the versions of `torch` or other relevant libraries please (e.g. `conda list`)?

**Comment by HRI-sxw** [comment]
apex==0.1
asttokens==2.0.8
backcall==0.2.0
certifi==2022.6.15
charset-normalizer==2.1.1
debugpy==1.6.3
decorator==5.1.1
entrypoints==0.4
executing==1.0.0
filelock==3.8.0
huggingface-hub==0.9.0
idna==3.3
ipykernel==6.15.2
ipython==8.4.0
jedi==0.18.1
jupyter-client==7.3.5
jupyter-core==4.11.1
matplotlib-inline==0.1.6
nest-asyncio==1.5.5
numpy==1.23.2
packaging==21.3
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.2.0
prompt-toolkit==3.0.31
protobuf==3.20.1
psutil==5.9.2
ptyprocess==0.7.0
pure-eval==0.2.2
Pygments==2.13.0
pyparsing==3.0.9
python-dateutil==2.8.2
PyYAML==6.0
pyzmq==23.2.1
regex==2022.8.17
requests==2.28.1
six==1.16.0
stack-data==0.5.0
tensorboardX==2.5.1
tokenizers==0.12.1
torch==1.12.1+cu116
torchaudio==0.12.1+cu116
torchvision==0.13.1+cu116
tornado==6.2
tqdm==4.64.0
traitlets==5.3.0
transformers==4.21.1
typing-extensions==4.3.0
urllib3==1.26.12
wcwidth==0.2.5

**Comment by Xiao-wen-Sun** [comment]
> Hi @HRI-sxw - I am not able to repro this on my machine -- to help debug, would you mind sharing the versions of `torch` or other relevant libraries please (e.g. `conda list`)?
@shanemoon 
apex==0.1
asttokens==2.0.8
backcall==0.2.0
certifi==2022.6.15
charset-normalizer==2.1.1
debugpy==1.6.3
decorator==5.1.1
entrypoints==0.4
executing==1.0.0
filelock==3.8.0
huggingface-hub==0.9.0
idna==3.3
ipykernel==6.15.2
ipython==8.4.0
jedi==0.18.1
jupyter-client==7.3.5
jupyter-core==4.11.1
matplotlib-inline==0.1.6
nest-asyncio==1.5.5
numpy==1.23.2
packaging==21.3
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.2.0
prompt-toolkit==3.0.31
protobuf==3.20.1
psutil==5.9.2
ptyprocess==0.7.0
pure-eval==0.2.2
Pygments==2.13.0
pyparsing==3.0.9
python-dateutil==2.8.2
PyYAML==6.0
pyzmq==23.2.1
regex==2022.8.17
requests==2.28.1
six==1.16.0
stack-data==0.5.0
tensorboardX==2.5.1
tokenizers==0.12.1
torch==1.12.1+cu116
torchaudio==0.12.1+cu116
torchvision==0.13.1+cu116
tornado==6.2
tqdm==4.64.0
traitlets==5.3.0
transformers==4.21.1
typing-extensions==4.3.0
urllib3==1.26.12
wcwidth==0.2.5

**Comment by XiaowenSun-Lab** [comment]
@shanemoon  
Hi, 
I redownload the code, use the same env, and then the problem solved. 
Best, Xiaowen

**Comment by shanemoon** [comment]
(For documentation & for anyone who experiences similar issues -- it was reported that the issue has resolved after downloading the latest data & code updated in the recent commit.)
