### ISSUE TITLE
About visualize_bboxes.py

### ISSUE THREAD

**Issue by heyzude** [facebookresearch/simmc2#6]
Running `model/utils/visualize_bboxes.py` invokes error,
and most of the errors say that it couldn't load the specified name of json file or cannot draw_bboxes because such named jsonfile is not present. 

Errors mainly occur at  
https://github.com/facebookresearch/simmc2/blob/34cc505a218d06ca264ac360920f653aaca60bd6/model/utils/visualize_bboxes.py#L89 or https://github.com/facebookresearch/simmc2/blob/34cc505a218d06ca264ac360920f653aaca60bd6/model/utils/visualize_bboxes.py#L100 

I see that for some scenes only bbox.json files are present (not with scene.json) at `data/simmc2_scene_jsons_dstc10_public/public`, and the code uses scene.json file to load bbox information, so scenes only with bbox.json invokes `No such file or directory` error.

**Comment by satwikkottur** [comment]
Hello @heyzude ,

Thanks for your interest. The confusion arises from the fact that some of the scenes have a "m_" prefix to indicate multiple scenes per dialog during data collection. If you find missing scene jsons, a quick test would be to see if there is a scene json with and without the "m_" prefix. 

My latest commit adds this part when no scene is specified and default behavior of visualizing all scenes is used. Feel free to reopen the issue if this does not solve the issue.
