### ISSUE TITLE
Question about mm_dst model

### ISSUE THREAD

**Issue by Xiao-wen-Sun** [facebookresearch/simmc2#60]
Maybe some mistakes, but I am not sure.

1. As far as I understand, '3.Generate prediction for devtest data'  generated prediction 'simmc2.1_dials_dstc11_devtest_predicted.txt' for '4. Evaluate predictions for devtest data'.
but the value of  'path_output' and 'input_path_predicted' are not consistent 

2, In the results.
![mm_dst results](https://user-images.githubusercontent.com/86380173/190998301-86ec708b-cf4c-4604-8ed4-cb8664d36d1e.png)

I am confusing the reported results are SIMMC 2 or 2.1

**Comment by shanemoon** [comment]
Hello, thank you for your questions.

1. Your understanding is correct. We will check if there was a typo in the paths. In general, please feel free to change the `path_output` and `input_path_predicted` in the respective scripts to make them consistent.

2. We will soon update the results to reflect the SIMMC 2.1 baseline numbers. Thank you!
