### ISSUE TITLE
Subtask 4 b - length of the answer candidate list

### ISSUE THREAD

**Issue by Manuelvh44** [facebookresearch/simmc2#61]
Hello, I'm currently trying to implement a model for subtask 4b but I'm not able to find information about how long the list of answer candidates should be for the retrieval task. I would be really grateful for some clarification.

Thanks in advance and best regards
Manuel

**Comment by shanemoon** [comment]
Hi @Manuelvh44, thank you for your question. 

We apologize for the confusion -- for DSTC11 (3rd edition of SIMMC challenge), we have removed the retrieval task (4b from DSTC10) from the official tasks. For evaluating the quality of Assistant responses, we will only study Response Generation as the main tasks for DSTC11. Please refer to the latest task description in the [main page](https://github.com/facebookresearch/simmc2). Thank you!
