### ISSUE TITLE
Questions:

### ISSUE THREAD

**Issue by Xiao-wen-Sun** [facebookresearch/simmc2#62]
Hi,
Could you share the hyperparameters of the baseline?
Best,
Xiaowen

![subtask1](https://user-images.githubusercontent.com/86380173/191918443-1e0e758e-fb2a-41ac-8a10-60c2fbb82bb0.png)

**Comment by satwikkottur** [comment]
Hello @XiaowenSun-Lab ,

Thanks for your interest. These results are with the default hyperparameters present in `train_model.py`. Please feel free to re-open the issue if this does not address it.
