### ISSUE TITLE
Question about subtask3

### ISSUE THREAD

**Issue by rungjoo** [facebookresearch/simmc2#7]
As mentioned in the paper we need to predict belief state (intents and slots) in subtask3.
![image](https://user-images.githubusercontent.com/48037590/123230026-cdde7280-d511-11eb-81e2-fd406e3607a7.png)

In the example data below, is it correct that the blue box "act" corresponds to "intent", and the green and red boxes "slot-values" and "request_slots" correspond to slots?
![image](https://user-images.githubusercontent.com/48037590/123230215-f8303000-d511-11eb-96df-1a572a64140d.png)

Thanks

**Comment by satwikkottur** [comment]
Hello @rungjoo ,

Apologies for getting back late. This is indeed correct. Thanks for your interest!

Feel free to reopen the issue if you have more questions.
