### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by JChiyah** [facebookresearch/simmc2#8]
Hi,

I think some of the links in the README.md are broken or files are missing. For instance, the following:

`
Please check the [task input](./TASK_INPUTS.md) file for a full description of inputs
for each subtask.
`

It references TASK_INPUTS.md but I cannot find the file anywhere in the repository and opening it takes me to a 404 Not Found webpage. Are there files missing from the repo by any chance? Thanks! :)

**Comment by shanemoon** [comment]
Hi @JChiyah , thank you for raising this issue & for your interest in the SIMMC2 track.

The mentioned doc (TASK_INPUTS) will summarize & clarify what input fields are allowed at training / inference time. We will soon make the link available - thank you for your patience!

In general, at the training time, you can use all of the multimodal information to train your model.
At the inference time (e.g. for the test set), participants can use the object bbox information, but not the ground-truth metadata (e.g. color, pattern, etc.). Models will have to infer this information from a vision model.

**Comment by bambidz** [comment]
Hi @shanemoon,
Is the scene.json (cloth_store_1416238_woman_10_0_scene.json) which has the up,down,left,right relationships of the objects useable during inference?
I understand that I cannot use the ground-truth metadata and able to use the bbox information.
Thanks in advance!

**Comment by satwikkottur** [comment]
Hello @JChiyah ,

We have uploaded the inputs for each task [here](https://github.com/facebookresearch/simmc2/blob/master/TASK_INPUTS.md). Please take a look and feel free to reopen the issue if you have more questions. Thanks!
